version: "3"

services:

  todoback:
    build: ./todo-app/back-end
    ports:
      - "3001:3001"
    networks:
      - rede-virtual-1

  todofront:
    build: ./todo-app/front-end
    ports:
      - "3000:3000"
    depends_on:
      - todoback
    environment:
      - REACT_APP_API_HOST=todoback
    networks:
      - rede-virtual-1

  todotests:
    build: ./todo-app/tests
    depends_on:
      - todoback
      - todofront
    environment:
      - FRONT_HOST=todofront
      - FRONT_PORT=3000
    networks:
      - rede-virtual-1

networks:
  rede-virtual-1: